Feature/tutorial screen
MathiasRossen/onboarding-app pull request #3
Opened 2024-01-16 12:28 UTC by MathiasRossen

Added DataStore and ended up using it without RxJava due to not being able to write to it

2024-01-17 12:16 UTC, daimis requested changes
Also, read about commit messages and naming conventions.

2024-01-17 12:16 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/MainActivity.kt
>          val sourcesScreenViewModel: SourcesScreenViewModel by viewModels()
Wrong scope. Should be as global value for activity

2024-01-17 12:16 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/MainActivity.kt
> +        }
This should be an inside view model. The view model tells the view what to do.

For example: view model has state/liveData to assign/post value to open a new screen.

2024-01-17 12:16 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/TutorialActivity.kt
> +        }
Shared preferences should be wrapped and injected into view model. You can look for examples in play app.

`
@Provides
    @Singleton
    fun provideSharedPreferences(@ApplicationContext context: Context): SharedPreferences =
        context.getSharedPreferences(BuildConfig.APPLICATION_ID, MODE_PRIVATE)
`
The inject for the hilt.

2024-01-17 12:16 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/TutorialActivity.kt
> +        }
Similar to the above. As you move shared preferences it will be gone from here.

Also, try to avoid putting static methods and use them outside of class scope.

2024-01-17 12:16 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/tutorial/TutorialPages.kt
> +fun TutorialPageTwo(onButtonClick: () -> Unit) {
If pages mean screens you should separate them into different classes. The main reason for that is better for readability. Will make this composable smaller and so on.

2024-01-17 12:35 UTC, MathiasRossen commented
> Also, read about commit messages and naming conventions.

Read an article from Antanas.
Still trying to figure out the correct way

2024-01-17 12:38 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/MainActivity.kt
>          val sourcesScreenViewModel: SourcesScreenViewModel by viewModels()
I need to load sources while the splash screen is running.
`installSplashScreen()` is called in this scope and needs a reference to the viewModel for this.

2024-01-17 14:15 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/MainActivity.kt
>          val sourcesScreenViewModel: SourcesScreenViewModel by viewModels()
It should be in the global scope for activity. Usually, it goes like this:
`
@AndroidEntryPoint
class MainActivity : AppCompatActivity() {
    private val sourcesScreenViewModel: SourcesScreenViewModel by viewModels()

    override fun onCreate(savedInstanceState: Bundle?) {
`

2024-01-17 14:27 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/MainActivity.kt
> +            }
All the logic should be in view model. Move if case inside the view model.

The exception is for flags which the part of the activity. For example: isTaskRoot etc.

2024-01-18 13:55 UTC, daimis approved these changes

2024-01-19 07:09 UTC, merged