Feature/news list screen
MathiasRossen/onboarding-app pull request #4
Opened 2024-01-19 09:10 UTC by MathiasRossen

2024-01-19 12:28 UTC, daimis requested changes

2024-01-19 12:28 UTC, daimis commented on app/build.gradle.kts
> +    implementation("joda-time:joda-time:${Versions.JODA_TIME_VERSION}")
Joda time is deprecated. Use java time

2024-01-19 12:28 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticleList.kt
> +fun ArticleList(articleListViewModel: ArticleListViewModel = viewModel()) {
Duplicate name `ArticleList`. Name it as `ArticleScreen`

Also, you can do it like this: 
`fun ArticleList(articleListViewModel: ArticleListViewModel = hiltViewModel())`

2024-01-19 12:28 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/SortButton.kt
> +data class SortButton(@StringRes val titleResource: Int, val sortState: SortState, val onClick: () -> Unit)
Never use higher-order functions﻿ inside the data class (`val onClick: () -> Unit`). You are making it very complicated. It is hard to follow. Can have huge side effects because you never know where the callback might land...

2024-01-19 12:28 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticleList.kt
> +    )
You can simplify this by making 
 ```
 enum class SortState(@StringRes name: Int,) {
    POPULAR_TODAY(R.string.something),
```
When for items do it like this:
```
items(SortState.entries) {
```

2024-01-19 12:28 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticleList.kt
> +                        if (sortButton.sortState == currentSortState) ButtonColors.defaultFilled() else ButtonColors.defaultTonal()
The soft limit for the line is 100 symbols. The hard limit is 120. Do not exceed it. Use brackets instead.

2024-01-19 12:28 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/sources/SourcesScreen.kt
> +    sourcesScreenViewModel: SourcesScreenViewModel = viewModel(),
hiltViewModel

2024-01-19 12:28 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/utils/LocalDateTimeAdapter.kt
> +class LocalDateTimeAdapter {
Why it is an adapter? Try to avoid names which android uses for the framework.
Better name is formatter.

2024-01-19 12:28 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/models/Article.kt
> +    val publishedAt: LocalDateTime,
This class is the response to an article. Should not be modified.
We are doing it like this -> response is the response -> when mapper, to map data into required data for screen.

If you wonder why. It's because the same response can be reused multiple times and can have multiple mappers for different views.

2024-01-19 12:28 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticleItem.kt
> +                .height(24.dp),
It can be just `.size(24.dp)`

2024-01-19 12:28 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticleListViewModel.kt
> +            if (sortState.value == SortState.POPULAR_TODAY || sortState.value == SortState.POPULAR_ALL_TIME) NewsApiService.SORT_BY_POPULAR else NewsApiService.SORT_BY_PUBLISHED_AT
Rearrange the code.

2024-01-19 12:32 UTC, MathiasRossen commented on app/build.gradle.kts
> +    implementation("joda-time:joda-time:${Versions.JODA_TIME_VERSION}")
There are requirements for API 24 and java.time is supported from API 26

2024-01-19 12:37 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/utils/LocalDateTimeAdapter.kt
> +class LocalDateTimeAdapter {
Moshi documentation uses 'Adapter' for their examples:
https://github.com/square/moshi#custom-type-adapters

2024-01-22 14:14 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticleItem.kt
> +            Divider(modifier = Modifier.run { height(dimensionResource(id = R.dimen.base_divider_size)) })
Isn't the same as` Modifier.heiht`?

2024-01-22 14:14 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticlesScreen.kt
> +                        if (sortState == currentSortState) {
If it's enough space `if` statement can be put on the same line.

2024-01-22 14:14 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticlesScreen.kt
> +                    }
This should be inside view model.
Then it is possible to replace all 3 click events with one:
`onSortOptionClick: (sortState: SortState) -> Unit`

2024-01-22 14:14 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticlesScreen.kt
> +fun ArticleList(
Same name `ArticleList`. Rename the first one to `ArticleScreen` and make the second one private.

2024-01-22 14:14 UTC, daimis commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/ArticleListViewModelTest.kt
> +        given(service.getArticlesFromSource(eq(sourceId), any(), any(), eq(null))).willReturn(
Don't use `any()` in unit test. Use the data which is passed for this case.

Because it is easy to make this unit test irrelevant. For example, if you change the type of parameter this unit test will still pass but maybe it should fail.

2024-01-24 07:32 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/models/Article.kt
> +    val publishedAt: LocalDateTime,
I think it doesn't make sense to keep the date as a string.
Wouldn't it be okay to modify the response that fits the entire system better? Especially in a case where you figured out that the earlier iteration of the class was fundamentally wrong?

I'm trying to revamp the responses/internal classes in another branch at the moment to keep them separate. One for Retrofit and one for Room.

2024-01-24 07:33 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticleItem.kt
> +            Divider(modifier = Modifier.run { height(dimensionResource(id = R.dimen.base_divider_size)) })
Yes.. I have no idea why I made this 😅

2024-01-24 07:35 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticlesScreen.kt
> +                        if (sortState == currentSortState) {
Maybe we should make formatter rules, so the auto formatter can catch things like this?

2024-01-24 14:22 UTC, daimis approved these changes

2024-01-24 14:22 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticlesScreen.kt
> +private fun ArticlesScreen(
Duplicate name again. Now we have two `ArticlesScreen`

2024-01-24 14:22 UTC, daimis commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/ArticlesScreenViewModelTest.kt
> +        given(service.getArticlesFromSource(eq(sourceId), eq(language), eq(sortBy), eq(date))).willReturn(
Most likely, argument matcher `eq()` is not required anymore.

2024-01-24 14:25 UTC, daimis commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticlesScreen.kt
> +                        if (sortState == currentSortState) {
I think it exists by default. Not the same but if it is more than 120 it will move the code to a new line. You just need to add in settings those limits.

2024-01-25 09:08 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/ArticlesScreen.kt
> +private fun ArticlesScreen(
Is function overloading a problem? I feel this ArticleScreen is descriptive because that's what it actually is.
Here's an example from Androids own sunflower example: https://github.com/android/sunflower/blob/main/app/src/main/java/com/google/samples/apps/sunflower/compose/plantlist/PlantListScreen.kt

Ofcourse I will just change it if it fits the code style better. I just want to pick your thoughts on this :)

2024-01-25 09:30 UTC, daimis approved these changes

2024-01-25 09:34 UTC, merged