Feature/article details screen
MathiasRossen/onboarding-app pull request #5
Opened 2024-02-01 09:15 UTC by MathiasRossen

2024-02-01 12:28 UTC, antsls requested changes

2024-02-01 12:28 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/details/ArticleDetailsViewModel.kt
> +                        println("horse $isFavorited")
Unnecessary code for debugging. Remove it.

2024-02-01 12:28 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/list/ArticlesScreenViewModel.kt
> +class ArticlesScreenViewModel @Inject constructor(
Avoid calling `viewModel` with words like `screen`. `ViewModel` should only correspond to business logic. In this case, better rename it to `ArticlesViewModel`.

2024-02-01 12:28 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/list/ArticlesScreenViewModel.kt
> +    private val sourceName: String = checkNotNull(savedStateHandle[SOURCE_NAME_KEY])
`checkNotNull` is an okay implementation. However if data is null, then application crashes and application in general is not stable.  Better add default values with the thought, that if there's no data, better to show error to the user, than crash the application.

2024-02-01 12:28 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/use_cases/ArticlesUseCase.kt
> +        Single.fromCallable { favoriteArticleDao.find(article.url) !== null }
Do you need to check reference equality using `!==` for nullability? I don't think that you need that. You can just use `!=`.

2024-02-01 12:28 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/use_cases/ArticlesUseCase.kt
> +    fun getIsArticleFavorited(article: Article): Single<Boolean> =
Typo in title.

2024-02-01 12:28 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/utils/OnboardingViewModel.kt
> +open class OnboardingViewModel(title: String = "NewsApp"): ViewModel() {
As a base `viewModel` it's better to be called as `BaseViewModel`, not `OnboardingViewModel`.

2024-02-01 12:28 UTC, antsls commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/ArticlesScreenViewModelTest.kt
> +        )
This fits into single line.

2024-02-01 12:28 UTC, antsls commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/ArticlesScreenViewModelTest.kt
> +            Single.just(mockArticles)
This fits into single line.

2024-02-01 12:28 UTC, antsls commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/ArticlesScreenViewModelTest.kt
>          )
This fits into single line.

2024-02-01 12:28 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/navigation/Screen.kt
> +        const val routeArticleDetails = "articleDetails/{articleUuid}"
As constants these values should be named in UPPER_SNAKE_CASE.

2024-02-01 13:57 UTC, antsls requested changes

2024-02-01 13:57 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/main/MainScreen.kt
> +                val canNavigateBack = navController.previousBackStackEntry !== null
`!=`  is more consistent than `!==`.

2024-02-01 13:57 UTC, antsls commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/ArticleDetailsViewModelTest.kt
> +        )
This fits into single line.

2024-02-01 13:57 UTC, antsls commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/ArticleDetailsViewModelTest.kt
> +        )
This fits into single line.

2024-02-01 13:57 UTC, antsls commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/ArticleDetailsViewModelTest.kt
> +        )
This fits into single line.

2024-02-01 13:57 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/list/ArticlesScreenViewModel.kt
> +                }
Missing `onError` implementation.

2024-02-01 13:57 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/details/ArticleDetailsViewModel.kt
> +                .subscribeOn(uiScheduler)
Should here be subscribe to UI scheduler? I think you should observe here.

2024-02-01 14:23 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/details/ArticleDetailsViewModel.kt
> +                .subscribeOn(uiScheduler)
Should I use observeOn? I'm having a hard time to figure out when to change between subscribeOn and observeOn

2024-02-02 08:51 UTC, antsls approved these changes

2024-02-02 08:51 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/data/article/FavoriteArticleDao.kt
> +
Line.

2024-02-02 08:51 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/articles/details/ArticleDetailsViewModel.kt
> +    private val articleUuid: String = checkNotNull(savedStateHandle[ARTICLE_UUID_KEY])
Add default return here.

2024-02-02 09:55 UTC, merged