Feature/favorites screen
MathiasRossen/onboarding-app pull request #7
Opened 2024-02-02 10:52 UTC by MathiasRossen

2024-02-06 12:24 UTC, antsls requested changes

2024-02-06 12:24 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesViewModel.kt
> +                }
Missing `onError` part.

2024-02-06 12:24 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesViewModel.kt
> +                    }
Missing `onError` part.

2024-02-06 12:24 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    favoritesViewModel.loadArticles()
Move article loading to viewModel's `init` part.

2024-02-06 12:24 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/NoFavoriteArticlesPlaceholder.kt
> +            Alignment.CenterVertically
Missing named parameter.

2024-02-06 13:03 UTC, antsls requested changes

2024-02-06 13:03 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    val articles by remember { favoritesViewModel.articles }
You don't need to create additional `remember` variable here. Use from `favoritesViewModel.articles`.

2024-02-07 06:19 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesViewModel.kt
> +                    }
I have a branch with error handling. Can we skip it here?

2024-02-07 06:48 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    favoritesViewModel.loadArticles()
The reason I want to call load here is to make sure I get favorite articles in case the list has changed.
If I move it into init, I will only load articles once and then when I start the favorites screen again, it will not update.
Let's say I go to the favorites screen -> the list is empty -> I go to the articles screen and favorite one of them -> Go back to the facorites screen -> the list is still empty.

2024-02-07 06:48 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    favoritesViewModel.loadArticles()
If there is a more elegant method to this, let me know :)

2024-02-07 08:17 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    favoritesViewModel.loadArticles()
In this particular case, you could implement #onResume() event.

```
@Composable
fun LifecycleOnResumeEvent(lifecycleOwner: LifecycleOwner, onResume: () -> Unit) {
    DisposableEffect(lifecycleOwner) {
        val observer = LifecycleEventObserver { _, event ->
            if (event == Lifecycle.Event.ON_RESUME) {
                onResume()
            }
        }
        lifecycleOwner.lifecycle.addObserver(observer)
        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
        }
    }
}
```
That way, viewModel's method `#loadArtcles()` can be called. However in this case it's better to rename it to `#onViewResumed()` or `#onResume()`.

2024-02-07 08:21 UTC, antsls requested changes

2024-02-07 08:21 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    val articles by favoritesViewModel.articles
Not sure, why you need `by` here. You can just assign value.

2024-02-07 08:21 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +            articles = favoritesViewModel.articles.value,
Reuse variable `articles`.

2024-02-07 08:25 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    val articles by favoritesViewModel.articles
It unwraps the mutableState to just the value and it still works with recomposition. Then I don't have to use articles.value

2024-02-07 08:26 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    favoritesViewModel.loadArticles()
Good point. I will try that

2024-02-07 08:27 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +            articles = favoritesViewModel.articles.value,
Good catch

2024-02-07 08:44 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    val articles by favoritesViewModel.articles
Then technically you can do this:
```
val articles = favoritesViewModel.articles.value
```

2024-02-07 09:11 UTC, MathiasRossen commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    favoritesViewModel.loadArticles()
Is there a downside to using
```    
LifecycleEventEffect(Lifecycle.Event.ON_RESUME) {
    favoritesViewModel.onResume()
}
```
instead?

2024-02-07 09:18 UTC, antsls commented on app/src/main/java/dk/mathiasrossen/onboardingapp/ui/favorites/FavoritesScreen.kt
> +    favoritesViewModel.loadArticles()
No, there isn't. Its implementation is practically the same, which I provided. Good notice.

2024-02-07 10:38 UTC, antsls requested changes

2024-02-07 10:38 UTC, antsls commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/FavoritesViewModelTest.kt
> +        viewModel.loadArticles()
Test will fail, method is private.

2024-02-07 10:38 UTC, antsls commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/FavoritesViewModelTest.kt
> +        viewModel.loadArticles()
Test will fail, method is private.

2024-02-07 12:56 UTC, antsls approved these changes

2024-02-07 12:56 UTC, antsls commented on app/src/test/java/dk/mathiasrossen/onboardingapp/viewmodels/FavoritesViewModelTest.kt
> +    fun loadArticles_favoriteArticlesAreLoaded() {
Rename to `onResume_favoriteArticlesAreLoaded`

2024-02-08 06:53 UTC, merged